// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtiVQzRHVfFnPt6XsxbR81oMu_2xq_3cA',
    appId: '1:1033846487212:web:d726c91169103c37974709',
    messagingSenderId: '1033846487212',
    projectId: 'my-cool-movie-app',
    authDomain: 'my-cool-movie-app.firebaseapp.com',
    storageBucket: 'my-cool-movie-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjnWHHycUfoV1-Tcx6L45xGmzzjYmJzT0',
    appId: '1:1033846487212:android:77d3adc4592d8d02974709',
    messagingSenderId: '1033846487212',
    projectId: 'my-cool-movie-app',
    storageBucket: 'my-cool-movie-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy13XCwpZESgUhKKnZ2UhSzV565SCdEVA',
    appId: '1:1033846487212:ios:cfa83cb02d916518974709',
    messagingSenderId: '1033846487212',
    projectId: 'my-cool-movie-app',
    storageBucket: 'my-cool-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.groupassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy13XCwpZESgUhKKnZ2UhSzV565SCdEVA',
    appId: '1:1033846487212:ios:cfa83cb02d916518974709',
    messagingSenderId: '1033846487212',
    projectId: 'my-cool-movie-app',
    storageBucket: 'my-cool-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.groupassignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtiVQzRHVfFnPt6XsxbR81oMu_2xq_3cA',
    appId: '1:1033846487212:web:1f63a098acfd519c974709',
    messagingSenderId: '1033846487212',
    projectId: 'my-cool-movie-app',
    authDomain: 'my-cool-movie-app.firebaseapp.com',
    storageBucket: 'my-cool-movie-app.firebasestorage.app',
  );

}